method_name: "frame_infer"

infer_dataset_top_directory: "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/infer_image_range_30_30/dir1_infer_image1000/"
csv_name: "image_attitude.csv"

weights_top_directory: "/home/ssd_dir/deep_gravity/train_on_luffy_35000"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/deep_gravity/infer_log/test_08_24_luffy/"
infer_log_file_name: "frame_infer_relust.csv"

resize: 224
mean_element: 0.5
std_element: 0.5